In [1]:
# idk this will do stuff
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import glob
from aqa_parsing_utilities import *
from data_center_model import *
from inference_scripts import *
from sklearn.preprocessing import normalize
import matplotlib as mpl
import time

mpl.rcParams['figure.dpi'] = 100

In [24]:
# loads model
sim_model = torch.load('models/model_v2_1.pth')
# generates initial P/R config and sim features (workload, util)
p_init = 1.0
r_init = 0.4
util = 0.8
#              Power   Tracking Error      QoS
cost_weights = [0.05,      0.7,             1    ]
cost_weights_w6 = [0.05,      0.8,             2    ]
cost_weights_w7 = [0.05,      1.2,             1   ]
# does GD optimization process

# Runs for each workload mix
start_time = time.time()
W3_P_record, W3_R_record,W3_W_record,_,_,_, W3_cost_record = model_pr_descent(p_init, r_init,'W3', sim_model,cost_weights=cost_weights)
print(time.time() - start_time)
start_time = time.time()
W4_P_record, W4_R_record,W4_W_record,_,_,_, W4_cost_record = model_pr_descent(p_init, r_init,'W4', sim_model,cost_weights=cost_weights)
print(time.time() - start_time)
start_time = time.time()
W5_P_record, W5_R_record,W5_W_record,_,_,_, W5_cost_record = model_pr_descent(p_init, r_init,'W5', sim_model,cost_weights=cost_weights)
print(time.time() - start_time)
start_time = time.time()
W6_P_record, W6_R_record,W6_W_record,_,_,_, W6_cost_record = model_pr_descent(p_init, r_init,'W6', sim_model,cost_weights=cost_weights_w6)
print(time.time() - start_time)
start_time = time.time()
W7_P_record, W7_R_record,W7_W_record,_,_,_, W7_cost_record = model_pr_descent(p_init, r_init,'W7', sim_model,cost_weights=cost_weights_w7)
print(time.time() - start_time)
start_time = time.time()
W8_P_record, W8_R_record,W8_W_record,_,_,_, W8_cost_record = model_pr_descent(p_init, r_init,'W8', sim_model,cost_weights=cost_weights)
print(time.time() - start_time)
start_time = time.time()

# generates the command and saves the weights
save_model_output(W3_P_record[-1],W3_R_record[-1],W3_W_record[-1],'hc24_w3_exp',exp_config = '\"../configs/hotcarbon24_exp/W3.ini\"')
save_model_output(W4_P_record[-1],W4_R_record[-1],W4_W_record[-1],'hc24_w4_exp',exp_config = '\"../configs/hotcarbon24_exp/W4.ini\"')
save_model_output(W5_P_record[-1],W5_R_record[-1],W5_W_record[-1],'hc24_w5_exp',exp_config = '\"../configs/hotcarbon24_exp/W5.ini\"')
save_model_output(W6_P_record[-1],W6_R_record[-1],W6_W_record[-1],'hc24_w6_exp',exp_config = '\"../configs/hotcarbon24_exp/W6.ini\"')
save_model_output(W7_P_record[-1],W7_R_record[-1],W7_W_record[-1],'hc24_w7_exp',exp_config = '\"../configs/hotcarbon24_exp/W7.ini\"')
save_model_output(W8_P_record[-1],W8_R_record[-1],W8_W_record[-1],'hc24_w8_exp',exp_config = '\"../configs/hotcarbon24_exp/W8.ini\"')


0.9109277725219727
0.8138301372528076
0.7901055812835693
0.8275432586669922
0.8407642841339111
0.8223574161529541
python -u master.py -p GPS -x hc24_w3_exp -g -b 1.1040105819702148 -r 0.6711599826812744 -u -z 0.000000  --profileConfig ../configs/q_grid_search/scc-applications-20200108.ini --experimentConfig "../configs/hotcarbon24_exp/W3.ini" --simulation 500 -o _hc24_w3_exp --perf-variation=0.00 --phase-length=10800 --random-seed=20
python -u master.py -p GPS -x hc24_w4_exp -g -b 1.0568987131118774 -r 0.8078736066818237 -u -z 0.000000  --profileConfig ../configs/q_grid_search/scc-applications-20200108.ini --experimentConfig "../configs/hotcarbon24_exp/W4.ini" --simulation 500 -o _hc24_w4_exp --perf-variation=0.00 --phase-length=10800 --random-seed=20
python -u master.py -p GPS -x hc24_w5_exp -g -b 0.9722650051116943 -r 0.6294496655464172 -u -z 0.000000  --profileConfig ../configs/q_grid_search/scc-applications-20200108.ini --experimentConfig "../configs/hotcarbon24_exp/W5.ini" --simul

In [18]:
print(W3_W_record)

[[0.125      0.125      0.125      ... 0.125      0.125      0.125     ]
 [0.12375238 0.12375    0.12375513 ... 0.12375049 0.12375381 0.13373548]
 [0.12310433 0.12251385 0.12257231 ... 0.12260925 0.12636986 0.1376767 ]
 ...
 [0.06390395 0.1056797  0.05969486 ... 0.03163356 0.11139851 0.56352395]
 [0.06429825 0.10620843 0.05997174 ... 0.03140405 0.11042442 0.56404907]
 [0.06468296 0.10671207 0.06023215 ... 0.03117803 0.10946728 0.56459427]]


In [1]:
print(31.2/175.4)
print(33.4/159.1)
print(26.4/147.3)
print(29.4/166.8)
print(29.9/171.6)
print(17.7/155.1)

0.17787913340935005
0.20993086109365178
0.17922606924643583
0.17625899280575538
0.17424242424242423
0.11411992263056092


In [2]:
(0.17787913340935005+0.20993086109365178+0.17922606924643583+0.17625899280575538+0.17424242424242423+0.11411992263056092)/6

0.171942900571363