In [1]:
from data_center_model import * 
import numpy as np

In [2]:
# makes model
set_trans = SetTransformer(dim_input=6, num_outputs=1, dim_output=16)

In [5]:
# makes three random "workloads" to test things
np.random.seed(42)
workload_1 = np.random.rand(1,10,6) # 1 batch, 10 workloads, of 6 variables long each 

output = set_trans(torch.tensor(workload_1).float())
print(output)

tensor([[[ 0.0157, -0.2579,  0.2114, -0.0371,  0.0885,  0.2248, -0.0854,
          -0.0005, -0.2201,  0.0646,  0.0631,  0.0809, -0.1305, -0.0085,
           0.0914, -0.1455]]], grad_fn=<ViewBackward0>)


In [25]:
# shows permutation invariance
np.random.seed(42)
workload_1 = np.random.rand(6) # new workload 1
workload_2 = np.random.rand(6) # new workload 2

workload_set_1 = np.zeros((1,10,6))
workload_set_1[0,0] = workload_1
workload_set_1[0,1] = workload_2

workload_set_2 = np.zeros((1,10,6))
workload_set_2[0,5] = workload_1
workload_set_2[0,2] = workload_2

output_1 = set_trans(torch.tensor(workload_set_1).float())
print(output_1)

output_2 = set_trans(torch.tensor(workload_set_2).float())
print(output_2)

print( (output_1-output_2)<0.000001) # floating points you know how they are 

tensor([[[ 0.0706, -0.1312,  0.1010, -0.0338,  0.0962,  0.1798, -0.0561,
           0.0123, -0.1442,  0.0397,  0.0426,  0.0286, -0.1059,  0.0485,
           0.0969, -0.1247]]], grad_fn=<ViewBackward0>)
tensor([[[ 0.0706, -0.1312,  0.1010, -0.0338,  0.0962,  0.1798, -0.0561,
           0.0123, -0.1442,  0.0397,  0.0426,  0.0286, -0.1059,  0.0485,
           0.0969, -0.1247]]], grad_fn=<ViewBackward0>)
tensor([[[True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True]]])


In [4]:
# shows zero-padding does not work with the S.T.
np.random.seed(42)
workload_1 = np.random.rand(6) # new workload 1
workload_2 = np.random.rand(6) # new workload 2

workload_set_1 = np.zeros((1,1,6))
workload_set_1[0,0] = workload_1
print(workload_set_1)


workload_set_2 = np.zeros((1,2,6))
workload_set_2[0,0] = workload_1
print(workload_set_2)


output_1 = set_trans(torch.tensor(workload_set_1).float())
print(output_1)

output_2 = set_trans(torch.tensor(workload_set_2).float())
print(output_2)

print( (output_1-output_2)<0.000001) # floating points you know how they are 

[[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]]]
[[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
  [0.         0.         0.         0.         0.         0.        ]]]
tensor([[[ 0.0291,  0.2343, -0.1522,  0.0346, -0.1781,  0.1200,  0.0839,
           0.1398,  0.0938, -0.0367,  0.0262, -0.0918, -0.1332, -0.0814,
           0.1843,  0.0121]]], grad_fn=<ViewBackward0>)
tensor([[[ 0.0205,  0.1423, -0.1899, -0.0137, -0.0709,  0.1044,  0.0240,
           0.1705,  0.0754,  0.0110,  0.0128, -0.0754, -0.1088, -0.1128,
           0.1018, -0.0231]]], grad_fn=<ViewBackward0>)
tensor([[[False, False, False, False,  True, False, False,  True, False,  True,
          False,  True,  True, False, False, False]]])
